# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tier3.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tier3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btier3.proto\x12\x05tier3\"\x1e\n\x0cScoreRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"W\n\rScoreResponse\x12\x11\n\traw_score\x18\x01 \x01(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05label\x18\x03 \x01(\t\x12\x10\n\x08model_id\x18\x04 \x01(\t2A\n\x0bTier3Scorer\x12\x32\n\x05Score\x12\x13.tier3.ScoreRequest\x1a\x14.tier3.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tier3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=22
  _globals['_SCOREREQUEST']._serialized_end=52
  _globals['_SCORERESPONSE']._serialized_start=54
  _globals['_SCORERESPONSE']._serialized_end=141
  _globals['_TIER2SCORER']._serialized_start=143
  _globals['_TIER2SCORER']._serialized_end=208
# @@protoc_insertion_point(module_scope)
