// src/router/mod.rs

// router implementation and proptests
pub mod tier2_runner;

// gRPC protobuf bindings generated by Tonic
pub mod tier2_proto {
    tonic::include_proto!("tier3");
}
pub mod tier3_proto {
    tonic::include_proto!("tier3");
}