// src/router/mod.rs

pub mod cascade;
pub mod dispatch;
pub mod tier1_runner;
pub mod tier2_runner;
pub mod tier3_runner;
pub mod tier4_runner;
pub mod tier5_runner;

// gRPC protobuf bindings generated by Tonic
pub mod tier3_proto {
    tonic::include_proto!("tier3");
}
